- cryosparc/job.py
Small fix to the Job.connect example (correct argument ordering)
> docs: fix to Job.connect example

- cryosparc/command.py
- cryosparc/job.py
- cryosparc/tools.py
- tests/conftest.py
- command_rtp access with `CryoSPARC.rtp`
- Fix job connect documentation
> Release v4.1.2 (tools)

- cryosparc/tools.py
- tests/conftest.py
- tests/test_tools.py
> fix: include created_by_user_id with create_job call

- cryosparc/tools.py
- tests/conftest.py
- tests/test_tools.py
> fix: correct connect argument handling in create_job

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- cryosparc/__init__.py
- cryosparc/include/cryosparc-tools/dataset.h
- cryosparc/job.py
- cryosparc/project.py
- cryosparc/tools.py
- docs/intro.md
- pyproject.toml
- setup.py
- tests/conftest.py
- tests/test_dataset.py
- tests/test_tools.py
- fix: error when creating a job with `CryoSPARC.create_job`
- fix: Dataset allocation error due to slot generation overflow
- docs: minor fixes
> Release v4.1.3

- docs/intro.md
Hi,
I noticed that the need for access to BASE_PORT + 5 is not mentioned in the Getting Started section.
> docs: update TCP port requirement

- cryosparc/job.py
- cryosparc/project.py
- cryosparc/tools.py
- cryosparc/workspace.py
- docs/_toc.yml
- docs/examples/custom-workflow.ipynb
- tests/conftest.py
- tests/test_tools.py
Including new `Job.interact` method for communicating with interactive jobs.
See preview here: https://cryosparc-tools-git-extensive-workflow-example-structurabio.vercel.app/examples/custom-workflow.html
> Docs: Extensive Workflow Example

- cryosparc/command.py
- cryosparc/tools.py
> Fix: capitalize HTTP method names

- Makefile
- README.md
Makefile should no longer be used for regular development
> chore: Specialize Makefile for CryoSPARC

- Makefile
- cryosparc/core.pyx
- cryosparc/util.py
- Fix Vercel build
- Fix type check issue
> v4.3 build fixes 

- cryosparc/core.pyx
When dataset is deleted, ensures internal object references can get garbage collected. Ported from `develop`
> Fix: ensure python object references decremented

- docs/intro.md
Recommend to install cryosparc-tools inside a virtual environment.
> Docs: include note about python virtual environment

- cryosparc/job.py
- docs/examples/custom-workflow.ipynb
To allow queuing master-direct jobs.
> Fix: Make job queue method lane argument optional

- CHANGELOG.md
- cryosparc/__init__.py
- cryosparc/core.pyx
- cryosparc/job.py
- docs/examples/custom-workflow.ipynb
- docs/intro.md
- pyproject.toml
- setup.py
- Fixed: `Job.queue` method `lane` argument is now optional when queuing directly to master
- Fixed: Dataset memory leak due to missing reference count decrease during dataset garbage collection
- Docs: pip update instructions
- Docs: Recommend Python environment as a prerequisite
> Release v4.3.1

- cryosparc/dataset.py
Easier to see which dataset load failed in an error traceback.
Example traceback:
```py
In [3]: d = Dataset.load("/Users/work/bench_big_dset_v2_old.cs")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/Development/cryoem-uoft/cryosparc-tools/cryosparc/dataset.py:564, in Dataset.load(cls, file, cstrs)
563 elif prefix != FORMAT_MAGIC_PREFIXES[CSDAT_FORMAT]:
--> 564     raise TypeError(f"Could not determine dataset format (prefix is {prefix})")
566 headersize = u32intle(f.read(4))
TypeError: Could not determine dataset format (prefix is b'\x94CSDAT')
The above exception was the direct cause of the following exception:
DatasetLoadError                          Traceback (most recent …
```
> Chore: Show path of dataset when exception encountered during loading

- cryosparc/command.py
- cryosparc/dataset.py
- cryosparc/errors.py
- cryosparc/job.py
- cryosparc/project.py
- cryosparc/spec.py
- cryosparc/tools.py
- cryosparc/workspace.py
- docs/_toc.yml
- docs/api/errors.rst
- CommandClient never raises `AssertionError`, only `CommandError`
- More helpful error message when CryoSPARC reports that slot specification is invalid
> Feat: Improved Command error handling and slots errors documentation

- CHANGELOG.md
- cryosparc/__init__.py
- cryosparc/command.py
- cryosparc/spec.py
- pyproject.toml
- setup.py
- Correct command response error data formatting
> Release v4.4.1

- .github/workflows/python-package.yml
> CI: update actions to use Node.js 20

- cryosparc/job.py
- tests/conftest.py
- tests/test_job.py
Official way of setting cluster variables.
> Feat: add cluster_vars to job.queue

- cryosparc/spec.py
Including `volume_multi` type.
> Fix: add v4.5 data types

- cryosparc/spec.py
- cryosparc/tools.py
https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/bild.html
Needed for internal plotting interface update.
> Feat: add Chimera bild file to allowed text formats

- .pre-commit-config.yaml
- cryosparc/dataset.py
- docs/examples/connect_series_to_class3D.ipynb
- tests/test_dataset.py
- Update pre-commit config
- Ensure ruff check doesn't only check imports
- Fix various type issues
> Fix: correct pre-commit lint config

- .pre-commit-config.yaml
- cryosparc/dataset.py
- cryosparc/job.py
- cryosparc/util.py
> chore: update pre-commit deps

- cryosparc/api.py
And headers. Suggested by Nicholas.
> fix(spm): exclude API client kwargs specified as None from query 

- cryosparc/api.pyi
- cryosparc/models/asset.py
- cryosparc/models/job.py
- cryosparc/models/job_register.py
- cryosparc/models/job_spec.py
- cryosparc/models/project.py
- cryosparc/models/session.py
- cryosparc/models/tag.py
- cryosparc/models/user.py
- cryosparc/models/workspace.py
- cryosparc/tools.py
- tests/conftest.py
- tests/controllers/test_job.py
Ensures computed fields and other recently-added fields and API changes are accessible
> fix: update generated models to include latest version with computed fields

- cryosparc/api.pyi
- cryosparc/controllers/job.py
- cryosparc/models/job_spec.py
- cryosparc/models/user.py
- tests/conftest.py
- tests/controllers/test_job.py
- tests/test_tools.py
Inputs are now objects instead of just lists.
> refactor: updated models with expanded sync input/output schemas

- cryosparc/mrc.py
Writing MRCs should cast to float32
> Feat(spm): Writing MRCs should cast to float32

- cryosparc/job.py
- New `Job.connect_result` method
- New `Job.disconnect_result` method
> feat: connect/disconnect low-level results for job

- .github/workflows/python-package.yml
With recommended settings to get linux builds to work.
> ci: update to cibuildwheel v3 action

- cryosparc/api.pyi
- cryosparc/models/asset.py
- cryosparc/models/auth.py
- cryosparc/models/event.py
- cryosparc/models/job_spec.py
- cryosparc/models/scheduler_target.py
- cryosparc/models/session.py
- cryosparc/models/user.py
That is, values that are Literals and Enums with a single item
> fix: correct generated models with const types
