cryoem-uoft/cryosparc-tools

- cryosparc/dataset.pxd
- cryosparc/dtype.py
In dataset.pxd
Currently dataset type is Py_ssize which is signed and of variable size, whereas dataset.h uses uint64_t. This may be leading to some alignment issues.
> fix: match cython types to C ones

- cryosparc/include/cryosparc-tools/dataset.h
- tests/test_dataset.py
Without this we are limited to ~32k datasets in memory. Includes test to catch similar issues
> fix: correct MASK_IDX bitshift in C dataset

- CHANGELOG.md
- cryosparc/__init__.py
- cryosparc/dataset.pxd
- cryosparc/dtype.py
- cryosparc/include/cryosparc-tools/dataset.h
- pyproject.toml
- setup.py
- tests/test_dataset.py
- match cython types to C ones
- use correct numpy object type
- correct MASK_IDX bitshift in C dataset (fixes limit on number of active datasets)
> Release v4.1.1

- cryosparc/command.py
- cryosparc/tools.py
I think it would be usefull to also be able to use command_rtp. Although a proper reference is missing, functions can be looked up from cryosparc_command/command_rtp/__init__.py. Maybe a test_connection could be added to command_rtp in next cryosparc release.
> feat: Add support for command_rtp

- cryosparc/include/cryosparc-tools/dataset.h
- tests/test_dataset.py
Happens then the same dataset memory slot gets filled up and deallocated many times
> fix: generation counter overflow on dataset slot

- cryosparc/command.py
TimeoutError is only available in 3.10, 3.9 and older require socket.timeout
> Fix: correctly catch command request timeout

- Makefile
- Default Python 3.10 build for CryoSPARC bundling
> chore: python 3.10

- .gitignore
- cryosparc/core.pyx
- cryosparc/dataset.pxd
- cryosparc/dataset.py
- cryosparc/include/cryosparc-tools/dataset.h
During stream compression. Retrieve column data again when the underlying dataset gets moved due to string allocation.
> Fix: prevent dellocated memory access

- cryosparc/include/cryosparc-tools/dataset.h
- setup.py
This is mostly trivial, just reducing the warning count: mainly pointer casts, signed/unsigned comparisons
> Eliminate some warnings

- cryosparc/command.py
URLError is raised when the command client can't connect to the command server. This may happen during server restarts or temporary losses in connection. With this change, if the connection is restored within 1 minute (by default), the request succeeds. Otherwise, it raises an error like before.
Example output (with shortened retry interval):
```py
❯ CRYOSPARC_COMMAND_RETRY_SECONDS=5 python
Python 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00) 
[GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cryosparc.command import CommandClient
>>> cli = CommandClient(port=61102)
>>> # command server goes down
>>> cli.show_scheduler_targets()
<stdin>:1: UserWarning: *** CommandClient: (http://localhost:61102/api) URL Error [Errno …
```
> Feat: retry command requests when URLError is raised

- cryosparc/include/cryosparc-tools/dataset.h
- this fixes a bug when including `dataset.h` in another file, where the compiler throws errors like:
```
cryosparc_tools/cryosparc/include/cryosparc-tools/dataset.h:64:98: error: unknown type name 'size_t'
64 | int         dset_setstr (uint64_t dset, const char * colkey, uint64_t index, const char * value, size_t length);
```
> Fix(Dataset): Include `stddef.h` in forward declaration section

- cryosparc/dataset.py
This reduces weirdness for clients that use Dataset and are expecting bytes, including command_vis
> Fix: only ever stream bytes from Dataset.stream()

- .github/workflows/python-package.yml
- Updated to the latest `pypa/cibuildwheel` action
- Ensure dedicated x64 and ARM builds for macOS
- ARM builds for Linux
> CI: Python 3.11 and 3.12 package builds

- cryosparc/__init__.py
- cryosparc/tools.py
- pyproject.toml
- setup.py
- tests/conftest.py
Example output:
```
In [1]: from cryosparc.tools import CryoSPARC
In [2]: cs = CryoSPARC(base_port=62000)
<ipython-input-2-3c3de64e7601>:1: UserWarning: CryoSPARC instance localhost:62000 with version v4.4.0 may not be compatible with current cryosparc-tools version v4.3.1.
To install a compatible version of cryosparc-tools:
pip install --force cryosparc-tools~=4.4.0
Or, if running a CryoSPARC pre-release or private beta:
pip install --force https://github.com/cryoem-uoft/cryosparc-tools/archive/refs/heads/develop.zip
cs = CryoSPARC(base_port=62000)
In [3]:
```
> Docs: show warning when connecting to incompatible CryoSPARC

- cryosparc/job.py
- cryosparc/project.py
May I gently suggest that the directories of `Project`s and `Job`s should be a properties instead (i.e., `Project.dir` instead of `Project.dir()`).
I realize this is a breaking change so feel free to ignore, it's very nitpicky.
> Project.dir and Job.dir should be properties

- docs/examples/connect_series_to_class3D.ipynb
- docs/examples/delete-rejected-exposures.ipynb
This should have been done as part of b4233bc, I apologize. `job.dir()` will now throw an error, examples should use `job.dir`.
> Fix .dir() documentation examples

- cryosparc/dataset.py
- tests/test_dataset.py
Useful when appending on a loop and want to keep fields around
> Fix: keep fields when appending empty datasets

- cryosparc/dataset.py
- tests/test_dataset.py
> Fix: keep fields when unionizing empty datasets

- cryosparc/core.pyx
- cryosparc/dataset.py
So that adding rows does not silently fail.
> Fix: raise explicit memory error when dataset allocation fails

- cryosparc/dataset.py
- tests/test_dataset.py
Make sure `exclude_uid` param works. Reported by Harris.
> Fix: correct Dataset.descr() implementation

- .github/workflows/python-package.yml
- Updated to pypa/cibuildwheel@v2.17.0 to avoid Windows build crash
- Separate artifact uploads to keep names unique due to breaking changes in actions/upload-artifact@v4
> CI: Windows and Artifact upload build fixes

- cryosparc/dataset.py
- New `rename` param for filter prefix to allow pulling out a renamed subset of fields in one shot
- New `is_equivalent` method to check whether datasets have identical fields that may be out of order
- Require that `copy` param is specified as kwarg
- Removed load_cached method
> Refactor: Dataset interface updates for future improved job I/O

- .pre-commit-config.yaml
- cryosparc/column.py
- cryosparc/dataset.py
- pyproject.toml
- Looser numpy version requirement
- `__array_wrap__` deprecation fix
- Replace `np.array(a, copy=False)` with `np.asarray(a)`
> Numpy 2.0 support 

- .pre-commit-config.yaml
- cryosparc/__init__.py
- cryosparc/column.py
- cryosparc/dataset.py
- cryosparc/spec.py
- pyproject.toml
- setup.py
- Add missing datatypes (#89)
- Numpy 2.0 support (#90)
> Release v4.5.1

- cryosparc/column.py
- cryosparc/dataset.py
- cryosparc/dtype.py
- cryosparc/job.py
- tests/conftest.py
- tests/test_dataset.py
- tests/test_dataset_bench.py
- New `Dataset.inspect` function for reading dataset headers
- Use chunked mmap loading for numpy arrays
- Break `load` into helper functions
> Refactor: Dataset load memory optimizations

- .pre-commit-config.yaml
- CHANGELOG.md
- cryosparc/__init__.py
- cryosparc/column.py
- cryosparc/dataset.py
- cryosparc/dtype.py
- cryosparc/job.py
- cryosparc/spec.py
- cryosparc/tools.py
- cryosparc/util.py
- docs/examples/connect_series_to_class3D.ipynb
- pyproject.toml
- setup.py
- tests/conftest.py
- tests/test_dataset.py
- tests/test_dataset_bench.py
- `Dataset.is_equivalent` method to check if two datasets have identical fields, but in a different order
- `Dataset.inspect`  class method which accepts a path to a dataset and returns its header without loading the entire dataset from disk
- Load a subset of dataset fields with `Dataset.load`  by specifying `prefixes` or `fields` keyword arguments
- Support for uploading job assets in `bild` format
- `ExternalJob.add_output` method now expects `alloc` argument to be specified as a keyword arg
- Dataset methods which accept a `copy` argument now expect it to be specified as a keyword arg
- Significantly reduced memory usage when loading large datasets with `Dataset.load`
> Release v4.6.0

- .github/workflows/python-package.yml
- bump pypa/cibuildwheel to v2.20.0
- allow testing build by including `[ci test build]` in the commit message ([figured out how to do it from this discussion](https://github.com/orgs/community/discussions/28474))
> CI: build fixes for v4.6

- cryosparc/project.py
Was `job` a typo, should be `project`?
> potential typo in doc string

- .github/workflows/python-package.yml
- .pre-commit-config.yaml
- cryosparc/dataset.py
- pyproject.toml
Note that latest pypa/cibuildwheel we were using was already creating Python 3.13 builds for the latest releases.
> ci: python 3.13 support

- cryosparc/errors.py
- cryosparc/job.py
Raises informative error message before external job is submitted to command server.
> fix: prevent queueing or killing external jobs

- cryosparc/job.py
- tests/conftest.py
- tests/test_job.py
Only allow alphanumeric characters and underscores for custom input/output names. This ensures that names with slashes or other special characters do not break the path when saving external results.
> fix: prevent invalid external job input/output group names

- .github/workflows/python-package.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- cryosparc/__init__.py
- cryosparc/dataset.py
- cryosparc/errors.py
- cryosparc/job.py
- pyproject.toml
- setup.py
- tests/conftest.py
- tests/test_job.py
- Added: Python 3.13 support
- Fix: Disallow non-URL-encodable characters when creating external job inputs and outputs
- Fix: Prevent queuing and killing external jobs (must use `job.start/job.stop()` or `with job.run()`)
> Release v4.6.1

- cryosparc/dataset.py
- tests/test_dataset.py
When saving and loading a dataset. Fixes an error that occurs when saving an external output.
> fix: correct stream implementation when dataset is empty

- .pre-commit-config.yaml
- cryosparc/api.py
- cryosparc/dataset.py
- cryosparc/errors.py
- cryosparc/json_util.py
- cryosparc/models/auth.py
- cryosparc/registry.py
- cryosparc/stream.py
- cryosparc/stream_registry.py
- pyproject.toml
Uses OpenAPI schema to generate methods API instead of JSONRPC. A future pull request will include a type stub for the generated methods.
> feat(spm): initial REST API client for CryoSPARC

- cryosparc/errors.py
Example:
```py
In [3]: api.start_and_migrate(license_id='12312')
...
APIError: *** [API] (PUT http://cryoem0.sbi:61004/start, code 401) received error response
Response data:
{
"detail": "Invalid License-Id header"
}
```
> fix(spm): show response data in API error messages

- cryosparc/api.py
- cryosparc/json_util.py
If given an enum list of enums, it should encode their values.
> fix(spm): correctly encode enums in query params and headers

- cryosparc/api.py
Use `model_validate(data)` instead of `__init__(**data)` when parsing JSON from the API to ensure that special model validators which return a different type have their results interpreted correctly by pydantic. This affects event models.
> fix(spm): correctly parse pydantic model results

- cryosparc/api.pyi
- cryosparc/auth.py
- cryosparc/cli.py
- cryosparc/constants.py
- cryosparc/platform.py
- cryosparc/session.py
- cryosparc/tools.py
- tests/conftest.py
- tests/test_cli.py
Addresses #64
Run a login command that saves an authentication token to the user `~/.config` directory. This allows running cryosparc-tools scripts without storing plain-text passwords on disk or environment variables.
```
❯ python -m cryosparc.tools login --help
usage: cryosparc.tools login [-h] [--url URL] [--email EMAIL] [--password PASSWORD] [--expires EXPIRES]
options:
-h, --help           show this help message and exit
--url URL            CryoSPARC web URL, e.g., http://localhost:39000
--email EMAIL        login email, prompts when unspecified
--password PASSWORD  login password, prompts when unspecified
--expires EXPIRES    token expiration date in format YYYY-MM-DD, cannot be more than one year in the future, defaults to 14 days from now.
```
> feat: secure command-line login

- cryosparc/dataset.py
Allows showing dataset without first casting it to a dataframe
Demo:
[Relevant IPython docs](https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#:~:text=_repr_html_,-:%20return%20raw%20HTML).
> feat: dataset to HTML method for jupyter

- cryosparc/api.py
Expose JSON encoders in `APINamespace` for use with custom encoders
> feat(api): Exposure JSON encoders

- cryosparc/api.py
- cryosparc/dataset/dtype.py
- tests/conftest.py
- tests/test_cli.py
also adds a more specific check for basemodels when decoding responses in the api client
> refactor(spm): use clearer error message when getting data field dtype from dataset

- cryosparc/api.pyi
- cryosparc/controllers/job.py
- cryosparc/controllers/project.py
- cryosparc/controllers/workspace.py
- cryosparc/models/event.py
- cryosparc/models/job.py
- cryosparc/models/session.py
- cryosparc/search.py
- cryosparc/tools.py
- tests/conftest.py
- tests/controllers/test_job.py
- New `find_projects`, `find_workspaces` and `find_jobs` methods for relevant controllers. `find_jobs` includes filtering arguments.
- Avoid sending now-unnecessary kill command
> feat: find methods multiple projects, workspaces, jobs

- cryosparc/controllers/job.py
- cryosparc/controllers/project.py
- cryosparc/controllers/workspace.py
Close T-3676
Dedicated controller functions to change title and description.
> feat: set title and description on project, workspace, job

- cryosparc/json_util.py
Instead of python object mode. Fixes circular reference error when used on some models.
> fix: encode pydantic models with JSON mode

- cryosparc/api.pyi
- cryosparc/controllers/job.py
- tests/controllers/test_job.py
Update an existing log by providing a name for it. Can use the ID of a previously-logged event as a name. Named events are reset when adding a checkpoint.
For example, show a live progress bar in the job log.
```py
for pct in range(1, 10):
job.log(f"Progress: [{'#' * pct}{'-' * (10 - pct)}] {pct * 10}%", name="progress")
sleep(1)
```
> feat: update functionality for job.log with name argument
